### ISSUE TITLE
F-droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [dozingcat/MousePounce#8]
...since 1.1.1 is not yet tagged :)

https://f-droid.org/wiki/index.php?title=com.dozingcatsoftware.mouse_pounce/lastbuild_3&oldid=289260

**Comment by dozingcat** [comment]
`v1.1.1` tag is created. I'll send an F-droid pull request shortly.

**Comment by dozingcat** [comment]
Sent https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8676

**Comment by dozingcat** [comment]
1.1.1 is now available on F-droid.
